name: Run Fetch Script

on:
  schedule:
    - cron: '0 9 * * *'   # runs every day at 9am UTC
  workflow_dispatch:       # allows manual runs
permissions:
  contents: write
jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # adjust if needed

      - name: Install dependencies
        run: |
          pip install -r requirements.txt    

      - name: Run the script
        run: python DATA_DASHBOARD.py
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add datadump/*.parquet
          git commit -m "Update parquet files [auto]" || echo "No changes to commit"
          git push

        

