[server]
runOnSave = true
port = 8501
maxUploadSize = 200
maxMessageSize = 200

[runner]
magicEnabled = false

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#1E88E5"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif" 