[credentials]
server = "medicloud.database.windows.net"
database = "HMO_CBA_CLEARLINE"
username = "clearline_dbm"
password = "h8A:t@X@\\h4K/h\"v"
port = "1433"

[eaccount_credentials]
server = "192.168.1.10"
database = "eaccount"
username = "eaccount"
password = "Password@1"
port = "1433" 